server:
  port: 8990

spring:
  application:
    name: face-service
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# knife4j
knife4j:
  enable: true
  setting:
    language: zh-CN
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.github

# jetcache
jetcache:
  # 统计间隔，时间单位为分钟，0表示不统计
  statIntervalMinutes: 15
  # 是否把area添加到cacheName前作为key前缀
  areaInCacheName: false
  # 本地缓存配置
  local:
    default:
      # 缓存类型为linkedhashmap，还可以为caffeine(本地缓存框架)
      type: caffeine
      # key转换器，当前只有一个实现，fastjson
      keyConvertor: fastjson
      # 本地缓存元素限制
      limit: 100
      # 全局过期时间，十分钟 1000*60*5
      expireAfterWriteInMillis: 60000
  # 远程缓存配置
#  remote:
#    default:
#      # 缓存类型，采用redis，还支持tair
#      type: redis
#      # key转换器
#      keyConvertor: fastjson
#      # 序列化策略配置，可选java和kryo
#      valueEncoder: java
#      # 反序列化策略
#      valueDecoder: java
#      # 下面都是redis的配置
#      poolConfig:
#        minIdle: 5
#        maxIdle: 20
#        maxTotal: 50
#      host: localhost
#      port: 6379
#      password: 123456