server:
  port: 8902
spring:
  application:
    name: face-generator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatroom?rewriteBatchedStatements=true
    username: root
    password: 123qwe

